/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade04.genio;
import java.util.Random;
import javax.swing.JOptionPane; // Importa a classe para exibir caixas de diálogo

/**
 *
 * @author inque
 */
public class telaGenio extends javax.swing.JFrame {

    /**
     * Creates new form telaGenio
     */
    public telaGenio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFalaGenio1 = new javax.swing.JLabel();
        lblFalaGenio2 = new javax.swing.JLabel();
        lblFalaGenio3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnResultado = new javax.swing.JButton();
        txttentativa = new javax.swing.JTextField();
        lblInfoTentativa = new javax.swing.JLabel();
        lblNumTentativas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFalaGenio1.setText("vou pensar...");
        getContentPane().add(lblFalaGenio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, -1, -1));

        lblFalaGenio2.setText("em um numero");
        getContentPane().add(lblFalaGenio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, -1, -1));

        lblFalaGenio3.setText("entre 0 e 5");
        getContentPane().add(lblFalaGenio3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\inque\\Documents\\NetBeansProjects\\prg03Inque\\src\\main\\java\\br\\com\\ifba\\atividade03\\imgs\\genio01 (1).png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 300));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 260, 250));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\inque\\Documents\\NetBeansProjects\\prg03Inque\\src\\main\\java\\br\\com\\ifba\\atividade03\\imgs\\balao02 (1).png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 210, -1));

        btnResultado.setText("adivinhar");
        btnResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadoActionPerformed(evt);
            }
        });
        getContentPane().add(btnResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 80, -1));
        getContentPane().add(txttentativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 220, 80, -1));

        lblInfoTentativa.setText("tentativas");
        getContentPane().add(lblInfoTentativa, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 20));

        lblNumTentativas.setText("3");
        getContentPane().add(lblNumTentativas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 30, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadoActionPerformed
        // new
        Random random = new Random();
        int num; // Declara a variável num fora do bloco try
        int numTentativas;

        try {
            num = Integer.parseInt(txttentativa.getText());//pega o texto(nunmero) digitado
            numTentativas = Integer.parseInt(lblNumTentativas.getText());

            int numAleatorio = random.nextInt(5);//recebe um random entre 0 e 5
            
            if(numTentativas > 0){
                numTentativas--;
                lblNumTentativas.setText(String.valueOf(numTentativas)); // Atualiza o label de tentativas na tela
                // Compara o número escolhido com o número aleatório
                if (num == numAleatorio) {
                    lblFalaGenio1.setText("");
                    lblFalaGenio2.setText("parabens esta");
                    lblFalaGenio3.setText("correto");
                    // Opcional:
                    int resposta = JOptionPane.showConfirmDialog(this, "Você acertou! Deseja jogar novamente?", "Fim de Jogo", JOptionPane.YES_NO_OPTION);
                    if (resposta == JOptionPane.YES_OPTION) { //reinicia o jogo ou fecha a janela
                        lblFalaGenio1.setText("vou pensar...");
                        lblFalaGenio2.setText("em um numero");
                        lblFalaGenio3.setText("entre 0 e 5");
                        numTentativas = 3;
                        lblNumTentativas.setText(String.valueOf(numTentativas));
                    } else {
                        this.dispose();
                    }
                
                } else {
                    lblFalaGenio1.setText("");
                    lblFalaGenio2.setText("numero errado");
                    lblFalaGenio3.setText("foi quase");
                }
            }else{
                //reseta todas as informacoes para um novo jogo
                JOptionPane.showMessageDialog(this, "0 tentativas restantes", "Erro", JOptionPane.ERROR_MESSAGE);
                numAleatorio = random.nextInt(5);
                lblFalaGenio1.setText("vou pensar...");
                lblFalaGenio2.setText("em um numero");
                lblFalaGenio3.setText("entre 0 e 5");
                numTentativas = 3;
                lblNumTentativas.setText(String.valueOf(numTentativas));
            }

            

        } catch (NumberFormatException e) {
            // Se ocorrer um erro ao tentar converter o texto para um número
            JOptionPane.showMessageDialog(this, "Por favor, digite apenas números!", "Erro", JOptionPane.ERROR_MESSAGE);
            txttentativa.setText(""); // Limpa o campo de texto para o usuário tentar novamente
            lblFalaGenio2.setText("tente adivinhar"); // Limpa as mensagens anteriores
            lblFalaGenio3.setText("");
        }
        
    }//GEN-LAST:event_btnResultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telaGenio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telaGenio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResultado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblFalaGenio1;
    private javax.swing.JLabel lblFalaGenio2;
    private javax.swing.JLabel lblFalaGenio3;
    private javax.swing.JLabel lblInfoTentativa;
    private javax.swing.JLabel lblNumTentativas;
    private javax.swing.JTextField txttentativa;
    // End of variables declaration//GEN-END:variables
}
