/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ifba.atividade03.view;
import java.time.Year;

/**
 *
 * @author inque
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAno = new javax.swing.JTextField();
        lblInfoIdade = new javax.swing.JLabel();
        lblInfoAno = new javax.swing.JLabel();
        lblResultado = new javax.swing.JLabel();
        btnResult = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        txtAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnoActionPerformed(evt);
            }
        });
        getContentPane().add(txtAno);
        txtAno.setBounds(170, 90, 64, 22);

        lblInfoIdade.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        lblInfoIdade.setText("Idade:");
        getContentPane().add(lblInfoIdade);
        lblInfoIdade.setBounds(100, 187, 48, 23);

        lblInfoAno.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        lblInfoAno.setText("Ano de Nascimento");
        getContentPane().add(lblInfoAno);
        lblInfoAno.setBounds(39, 95, 109, 18);
        getContentPane().add(lblResultado);
        lblResultado.setBounds(168, 103, 64, 20);

        btnResult.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/imgs/calculator_17143940 (1).png"))); // NOI18N
        btnResult.setText("calcular");
        btnResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultActionPerformed(evt);
            }
        });
        getContentPane().add(btnResult);
        btnResult.setBounds(80, 130, 91, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ifba/atividade03/imgs/profile_3135715.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 80, 260, 270);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultActionPerformed
        // TODO add your handling code here:
        // Recebe o ano digitado pelo usuário do campo de texto chamado 'txtAno'
        try {
            // recebe o ano digitado pelo usuario
            int anoNascimento = Integer.parseInt(txtAno.getText());

            // Obtém o ano atual usando a classe Year do Java 8+
            int anoAtual = Year.now().getValue();

            // Calcula a idade
            int idade = anoAtual - anoNascimento;

            // Atualiza o texto de um JLabel chamado 'lblResultado' com o valor da idade
            lblResultado.setText(String.valueOf(idade));
        } catch (NumberFormatException e) {
            // Trata o erro caso o usuário não digite um número válido no campo de texto
            lblResultado.setText("Ano Inválido!");
            // Opcionalmente, você pode exibir uma mensagem de erro mais amigável ao usuário
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, insira um ano válido.", "Erro", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnResultActionPerformed

    private void txtAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResult;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblInfoAno;
    private javax.swing.JLabel lblInfoIdade;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JTextField txtAno;
    // End of variables declaration//GEN-END:variables
}
